services:

  network-deploy-service:
    networks:
      - ms

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres "]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 1024m
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

networks:
  ms:
    driver: bridge